### ISSUE TITLE
cabal-helper-wrapper and stack

### ISSUE THREAD

**Issue by alanz** [DanielG/cabal-helper#7] opened 2015-08-06 19:12 UTC
If I install cabal-helper using a straightforward cabal install it autogens the value in `Paths_cabal_helper.hs` as

``` haskell
libexecdir = "/home/alanz/.cabal/libexec"
```

It is found for normal ghc-mod operations.

If I blow away the `.cabal/libexec` directory, and run ghc-mod from a stack install, the libexec path still gets set as above, even though the install directory is now in .stack-work, and the other paths in that file properly reflect this.

The particular case shows up in https://travis-ci.org/alanz/HaRe/builds/74307616

This is low priority for me, now I know what the problem is I can work around it for travis, but probably needs to be fixed some time.

**Comment by DanielG** [comment] 2015-08-07 01:51
Why would you blow away libexec/ in the first place D:

If you want it to end up in .stack-work then why not set --prefix to that? Figuring out where these things get installed to is hard enough as it is :p 

The problem is there is no such thing as a libexec_PATH so I kind of have to "hardcode" the path in this way, unless you have a better suggestion? But to me this seems like a bug in stack or whatever you're using to install it in the first place.

**Comment by robstewart57** [comment] 2015-09-30 21:12
Hi @DanielG I'm experiencing the same error you reported in stack issue 828 in [this comment](https://github.com/commercialhaskell/stack/issues/828#issuecomment-134072931). I.e.

> Couldn't find executable cabal-helper-wrapper in directory /home/rob/code/haskell/cabal-helper/.stack-work/install/i386-linux/lts-3.6/7.10.2/bin/

Because the `cabal-helper-wrapper` has instead been installed into directory:

```
/home/rob/code/haskell/cabal-helper/.stack-work/install/i386-linux/lts-3.6/7.10.2/libexec/cabal-helper-wrapper
```

I couldn't distill a solution from the follow on discussion on that thread. What can I do to successfully install cabal-helper and cabal-helper-wrapper with stack?

**Comment by cblp** [comment] 2015-11-02 14:37
+1

**Comment by seckcoder** [comment] 2015-11-04 21:14
+1

**Comment by mgsloan** [comment] 2016-01-13 00:21
+1

How about instead running `cabal install --bindir=...` when installing it?  Seems far less magical than this Setup.hs

**Comment by DanielG** [comment] 2016-01-13 00:31
How would that work when cabal-helper is installed as a dependency?

**Comment by mgsloan** [comment] 2016-01-13 00:35
Doesn't it get built by ghc-mod?

**Comment by DanielG** [comment] 2016-01-13 00:40
No it's just a dependency. The libexec executable then compiles the stuff in `CabalHelper/` at runtime that's the part that is triggered by ghc-mod via the cabal-helper library.

**Comment by mgsloan** [comment] 2016-01-13 00:42
I see..

How about installing it to the same binary path that ghc-mod is installed to?

**Comment by mgsloan** [comment] 2016-01-13 00:42
Sure, then it'll be available in the shell, but `cabal-helper-wrapper` is a long, clear name.  It won't cause any confusion.

This way, I can copy commandline invocations out of a verbose log, and try them out.

**Comment by DanielG** [comment] 2016-01-13 00:43
Are you actually having any problems? As far as I can tell no one is actually having any problems with this anymore.

**Comment by mgsloan** [comment] 2016-01-13 00:43
Uhh, except all the +1s?

Yes, the problem is that stack doesn't expect you to change the install directory

**Comment by DanielG** [comment] 2016-01-13 00:43
But it will clash with TAB completion on something like the `cab` prefix ;). I simply refuse not putting this thing into $libexec! It's an executable uses by a library, that's the damn definition of what should go into libexec.

**Comment by DanielG** [comment] 2016-01-13 00:45
If this was still a problem for the majority of people I'd be spammed with bug reports so obviously it's not a problem anymore.

**Comment by mgsloan** [comment] 2016-01-13 00:45
For the tab completion I've used, if `cabal` and `cabal-helper-wrapper` are both present, pressing TAB on `cab` will complete to `cabal`.

**Comment by DanielG** [comment] 2016-01-13 00:46
Anyways if stack doesn't expect me to do this then that's a bug in stack plain and simple so point me to an issue please. Setup.hs is something that exists for just this sort of purpose so I don't really see why I shouldn't be able to do this.

**Comment by mgsloan** [comment] 2016-01-13 00:49
Stack is passing `--bindir=/home/mgsloan/oss/kazu-yamamoto/.stack-work/install/x86_64-linux/lts-4.1/7.10.3/bin` to Setup.hs when configuring, and it's ignoring it.

**Comment by mgsloan** [comment] 2016-01-13 00:50
That said, fair 'nough, I see your point of view.

**Comment by DanielG** [comment] 2016-01-13 00:50
So? It also ought to pass `--libexecdir=..` and it's complying with that just fine. I tested this locally it gets installed into `./.stack-work/install/x86_64-linux/lts-4.1/7.10.3/libexec/cabal-helper-wrapper`.

**Comment by DanielG** [comment] 2016-01-13 00:52
So what exactly is the problem here again? ;)

**Comment by mgsloan** [comment] 2016-01-13 00:56
Well, the problem is that this seems overly complicated and prone to error.  I'm having a lot of trouble getting my changes to cabal-helper-wrapper to actually be reflected in execution.

Why not just have some default dir, like `.cabal-helper/Cabal-1.22.0.0`, where this stuff goes?  (my understanding is we need one per cabal)

**Comment by DanielG** [comment] 2016-01-13 00:58
Well why didn't you just say that. The executables that link against Cabal are cached in `~/.ghc-mod/cabal-helper` they include the cabal-helper and Cabal version in their name so they get properly invalidated when a new release comes out just not when you modify them locally. Just `rm -r ~/.ghc-mod/cabal-helper`

**Comment by DanielG** [comment] 2016-01-13 00:59
PRs welcome for adding a hash of the relevant source files in the file name instead of the cabal-helper version ;)

**Comment by mgsloan** [comment] 2016-01-13 01:00
Argh, yeah, that's really unexpected...

**Comment by DanielG** [comment] 2016-01-13 01:02
The files are read in here: https://github.com/DanielG/cabal-helper/blob/master/CabalHelper/Data.hs adding a hash should be easy.

**Comment by DanielG** [comment] 2016-01-15 18:45
I think the original issue here has been resolved so closing.

**Closed as completed by DanielG** 2016-01-15 18:45 UTC
